name: consumify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  getwidget: ^4.0.0
  google_fonts: ^6.1.0
  http: ^1.1.2
  just_audio: ^0.9.36
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.11.0
  string_scanner: ^1.2.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test_api: ^0.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/JSONS/songs.json
  
